version: "3"

services:
  nginx:
    container_name: nginx
    image: nginx
    depends_on:
      - php
      - pgsql
    ports:
      - 8080:80
    volumes:
      - "../excel:/var/www/html"
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"

  php:
    container_name: php
    build:
      dockerfile: "./php/Dockerfile"
    volumes:
      - "../excel:/var/www/html"
      - ./php/php.ini:/usr/local/etc/php/php.ini

  pgsql:
    container_name: pgsql
    image: postgres:15
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    ports:
      - 15432:5432
    volumes:
      - "./data:/var/lib/postgresql/data"

  mailcatcher:
    container_name: mailcatcher
    image: schickling/mailcatcher
    ports:
      - 1080:1080
      - 1025:1025